# Understanding Numpy 

In [1]:
# import all neccsarry libraries

import numpy as np
import matplotlib.pyplot as plt
import time

# Check NumPy version
print(f"NumPy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)

NumPy version: 2.3.3


creating Numpy Arrays

In [2]:
import numpy as np
import matplotlib.pyplot as plt
# 1D array: a simple sequence of numbers
# arr1d=np.array([1,2,3,4,5])
# print(arr1d)

# # 2D array: Think of this as a matrix of numbers with rows and columns
# arr2d= np.array([[1,2,3,4],[5,6,7,8]])
# print(arr2d)

# # 3D array: Think of these like a stack of 2D arrays
arr3D= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D)

# # creating array with Random
# ar1D=np.random.randn(4)
# print("Array1D\n",ar1D)

# ar2D=np.random.randn(4,4)
# print("Array2D\n",ar2D)

# ar3d=np.random.randn(2,4,4)
# print("Array3D\n",ar3d)

# creating array with range of numbers
# array1D=np.random.randint(1,10, size=4)
# print("Rand1\n",array1D)

# array2D=np.random.randint(1,31, size=(6,6))
# print("rand2\n",array2D)

# array3D=np.random.randint(1,41, size=(2,6,6))
# print("Rand3\n",array3D)

# # working with arange
# range_array=np.arange(0,10,2)
# int("range:\n",range_array)

# line_spacing=np.linspace(1,5,5)
# print("lines\n",line_spacing)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
