# Understanding Numpy

In [2]:
import numpy as np
import matplotlib.pyplot
import time
print(np.__version__)

2.3.3


Creating Numpy arrays

In [ ]:
#creating arrays from python lists
# 1D array: A simple sequence of number
arr1d= np.array([1,2,3,4,5])
print("1D array\n",arr1d)

# 2D array: Think of this as a simple matrix or table with rowa and column
arr2d= np.array([[1,2,3,4],[5,6,7,8]])
arr2d

#3D array:Think of this like a stack of 2D array
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D array:\n", arr3d)

ar3=np.array([[[1,2,3,4]]])
print('4x3mareix\n',ar3)
ar3.shape

### Creating special array in numpy

In [ ]:
# creating sprcial arrays filled with zeros
zeros=np.zeros((4,4))
print('zeeros array:\n',zeros)


# creating special arrays filed with ones
# ones=np.ones((3,3))
# print('ones array:\n',ones)

# # creating empty arrays
# empty=np.empty((2,4))
# print('empty array:\n',empty)

In [ ]:
# Range arraysn- like python range but more powerful
range_arr=np.arange(0,10,3)
print('arange array\n',range_arr)

# Linearly spaced arrays
linear_arr=np.linspace(0,10,5)
print('linear array:\n',linear_arr)

# logspace arrays
log_array=np.logspace(0,2,5)
print('log array:\n',log_array)


In [ ]:
# identity matrix
identity=np.eye(4)
print('identity matrix:\n',identity)

# diagonal matrix
np.diag([1,2,3,4])

# array filled with a specific number
np.full((4,3),8)


### Numpy data type

In [ ]:
# Explicit data types - control memory usage and precision
int_arr=np.array([1,2,3,4],dtype=np.int32)
print('int arrar:\n',int_arr)
int_arr.dtype

float_arr=np.array([[1,2,3],[3,4,5],[6,5,4],[5,3,1]],dtype=np.float64)
print('float array:\n',float_arr)
float_arr.dtype

converted=int_arr.astype(np.float16)
print('converted:\n',converted)

print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")
converted.itemsize

### Array propertes and attributes

In [ ]:
arr=np.random.randn(2,4,4)
print('arr display:\n',arr)

print('size:\n',arr.size)
print('shape:\n',arr.shape)
print('data type:\n',arr.dtype)
print('itemsize:\n',arr.itemsize)
print('ndim:\n',arr.ndim)

### Array indexing and slicing


Basic indexing

In [ ]:
print(float_arr)
print(float_arr[0,2])
print(float_arr[ 3, 2 ])
print(float_arr[:2])
print(float_arr[:1])
print('clero:\n',float_arr[2:])

# Advance indexing
indeces=np.array([0,1,3,3])

print('idices:\n',float_arr[indeces])
#print('fancy indexing:\n',float_arr[rol, coll])
float_arr.reshape(2,2,-1)

In [ ]:
# 2D fancy indexing - select row/column combination
arro=np.arange(16).reshape(4,4)
print('arrow shows\n',arro)

row=np.array([1,3])
col=np.array([3,2])
print('Advance indexing:', arro[row,col])
indoces=np.array([0,2])
print('indoces:\n',arro[indoces])

### Array reshaping and manipulaton

In [ ]:
arro.reshape(2, -1)

arro.reshape(2,2,-1)


In [107]:
# flattening - convert multi-dimensional array to 1D
flattened=arro.flatten()
arro

ravel=arro.ravel()
ravel

arro[0,0]=999
print('After modifying original:')
print('flattened(unchange):', flattened)
print('ravel:',ravel)

After modifying original:
flattened(unchange): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
ravel: [999   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]


### Transposing and swaping Axes

In [112]:
# 2D transposition - flip rows and columns
arr2d.shape
arr2d.T.shape

(4, 2)

In [ ]:
# Higher-dimensional transposition
arr3d=np.arange(24).reshape(2,3,4)
print('arr3d vector:\n',arr3d)

# Specify new axis order: (axis0, axis1, axis2) → (axis2, axis0, axis1)
transpose3d=arr3d.transpose(2,0,1)
print('Transpose 3d:\n', transpose3d)

# moveaxis is another way to rearrange axes
moved3d=np.moveaxis(arr3d,0,-1)
print('moved 3d:\n', moved3d)


### concatenating and splitting Arrays

- Combining and dividing arrays is fundamental for data manipulation

In [3]:
# concatenation - joining arrays along existing axis
arr1= np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

# concatenate along different axis
concat_rows=np.concatenate([arr1,arr2], axis=0)
concat_col=np.concatenate([arr1,arr2],axis=1)

print("Original arrays:")
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated vertically (axis=0):\n", concat_rows)
print("Concatenated horizontally (axis=1):\n", concat_col)

Original arrays:
Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Concatenated vertically (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated horizontally (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Convenient stacking functions
# vstack_result=np.vstack([arr1, arr2])
# hstack=np.hstack([arr1,arr2])
# dstack=np.dstack([arr1,arr2])

# print("vstack (vertical):\n", vstack_result)
# print("hstack (horizontal):\n", hstack)
# print("dstack shape:", dstack)  # Creates 3D array
# print("dstack shape:", dstack.shape)  # Creates 3D array

# Splitting arrays - opposite of concatenation
arr =np.arange(12).reshape(3,4)
print('show arr:\n', arr)
split_arr=np.split(arr, 3, axis=0)
print('split_arr:\n', split_arr)

for i, split_part in enumerate(split_arr):
    print(f"Part {i}:\n", split_part)


### Mathematical operation

- Element-wise Operation- The power of vectorization

In [ ]:
# Basic arithmetic operations work element-by-element
