In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
# A row of vector (1d)
v1=np.array([1,2,3,4])
print(v1)

# A column of vector (2d with shape 3x1)
v2=np.array([[3],[4],[4]])
print('2d vector:\n',v2)

[1 2 3 4]
2d vector:
 [[3]
 [4]
 [4]]


Vection Addition

In [ ]:
# Vector addition
a=np.array([2,3,4])
b=np.array([3,4,5])
sum_vector=a + b
print(sum_vector)

# Geometric interpretation in 2D
a_2d

[5 7 9]
