In [2]:
# import all neccsarry libraries

import numpy as np
import matplotlib.pyplot as plt
import time

# Check NumPy version
print(f"NumPy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)

NumPy version: 2.3.2


***Creating Numpy Arrays***

In [15]:
# Creating arrayfrom python list
arr_1d=np.array([1,2,3,4])
print('Array 1D:\n',arr_1d)

arr_2D=np.array([[1,2,3,4],[5,6,7,8],[9,1,3,5]])
print('Array 2D:\n',arr_2D)

arr_3D=np.array([[[1,2,3],[3,4,5],[7,8,9]],[[3,2,1],[6,5,4],[9,8,7]]])
print('Array 3D:\n',arr_3D)

empty = np.empty((2, 2)) 
print("Empty array (contains random values):\n", empty)


Array 1D:
 [1 2 3 4]
Array 2D:
 [[1 2 3 4]
 [5 6 7 8]
 [9 1 3 5]]
Array 3D:
 [[[1 2 3]
  [3 4 5]
  [7 8 9]]

 [[3 2 1]
  [6 5 4]
  [9 8 7]]]
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


*Creating special arrays in Numpy*

In [16]:
range_arr=np.arange(0,10,2)
print('Range array:\n',range_arr)

range_2arr=np.arange(5,20,3)
print(range_2arr)

Range array:
 [0 2 4 6 8]
[ 5  8 11 14 17]


In [17]:
# Identity matrix
iden=np.eye(4)
print('identity mat:\n',iden)

#diagonal matrix
diago=np.diag([2,4,6,8])
print('Diagonal mat:\n',diago)

# ARRAY filled with a specific number
fill_arr=np.full((4,4),7)
fill_arr

identity mat:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal mat:
 [[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

**Array Properties & Attributes**

In [28]:
# Create a sample 3D array for demonstration
# Think of this as 3 layers, each with 4 rows and 5 columns
arr=np.random.randn(4,5)
print(arr)

print('arr size:\n',arr.size)

print('Data type of arr:\n',arr.dtype)

carr=arr.astype(np.int32,)
print('Data type:\n',carr.dtype)

[[-0.721  1.005  1.237  0.485 -0.269]
 [ 1.762 -0.069 -0.104 -0.062 -0.358]
 [-0.19   1.104 -1.615 -1.454  2.447]
 [ 0.764  0.279  0.787 -0.588  1.109]]
arr size:
 20
Data type of arr:
 float64
Data type:
 int32


In [12]:
import sys
print('Current python version is:',sys.version)

Current python version is: 3.13.6 (tags/v3.13.6:4e66535, Aug  6 2025, 14:36:00) [MSC v.1944 64 bit (AMD64)]


Basic indexing- Accessing individual Elements

In [16]:
#indexing in one dimensional array 
arr1d=np.arange(0,10,2)
print(arr1d)

print(arr1d[2])

#indexing in 2D
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3],[8,7,6,5]])
print('2D Array:',arr2d)

print('showing:',arr2d[1,0])


print(arr2d[:, 0])

# indexing 3D
arr3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]],[[8,7,6],[5,4,0]]])
print('Array 3D:\n',arr3D)

print('indexing:\n',arr3D[[0,2],[1,1]])
print('2nd indexing:\n',arr3D[[0,1]])

[0 2 4 6 8]
4
2D Array: [[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [8 7 6 5]]
showing: 5
[1 5 9 8]
Array 3D:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[8 7 6]
  [5 4 0]]]
indexing:
 [[4 5 6]
 [5 4 0]]
2nd indexing:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [17]:
# Fancing indexing 
arr2d=np.arange(0,20,1).reshape(4,5)
print(arr2d)
row=np.array([0,3])
col=np.array([0,2])

print('Index:\n',arr2d[row,col])

# select entire rows using fancing indexing
selected_rows=arr2d[[1,2],:]
print('selected rows:',selected_rows)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Index:
 [ 0 17]
selected rows: [[ 5  6  7  8  9]
 [10 11 12 13 14]]


Array reshaping and manipulation 

In [ ]:
# start with a 1D array
arr=np.arange(0,10,2)
print(arr)

arr1= np.arange(10)
print(arr1)

arr0=np.arange(0,20).reshape(5,4)
print(arr0)

arr0.reshape(2,2,-1)

Transposing and swapping Axes

In [ ]:
arr2d= np.array([[1,2,3],[4,5,6]])
print(arr2d)
print('Original shape:\n',arr2d.shape)

print('Transposed shape:\n',arr2d.T)

# Alternative Transpose methods
print('Alternative transpose:\n',arr2d.transpose())

**Concatenating and Splitting Arrays**

- Combining and dividing arrays is fundamental for data manipulation

In [ ]:
# Concatenation - joining arrays along existing axes
arr1 =np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along different axes
concat_rows =np.concatenate([arr1,arr2], axis=0)    #stack vertically(add rows)
concat_cols=np.concatenate([arr1,arr2], axis=1)     # Stack horizontally (add columns)

print("Original arrays:")
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated vertically (axis=0):\n", concat_rows)
print("Concatenated horizontally (axis=1):\n", concat_cols)


In [ ]:
# Convenient stacking function 
# vstack_result=np.vstack([arr1, arr2])
# hstack_result=np.hstack([arr1,arr2])
# dstack_result=np.dstack([arr1,arr2])

# print("vstack (vertical):\n", vstack_result)
# print("hstack (horizontal):\n", hstack_result)
# print("dstack shape:", dstack_result) 
# print("dstack shape:", dstack_result.shape) 

# arr3=np.array([[[1,5],[2,6]],[[3,7],[4,8]]])
# print('My own generated 3D:\n',arr3)

# Splitting arrays - opposite of concatenation
arro=np.arange(0,12).reshape(4,3)
print('Arro image:\n',arro)

split_arro=np.array_split(arro,3, axis=1)
print(split_arro)

*Mathematical operation*

Element-wise operation - The power of vectorization

In [ ]:
# Basic arithmetic operations work element-by-element
arr1 = np.arange(0,12).reshape(3,4)
arr2 = np.array([10, 20, 30, 40])
arr3 = np.arange(10,22).reshape(4,3)

# All operations happen element-wise automatically
print('arri shape:\n',arr1)
print('Addition:\n',arr1 + arr2)
print("Subtraction:", arr2 - arr1) 
print("Multiplication:", arr1 * arr2) 
print("Division:", arr2 / arr1)
print('showing arr3:\n',arr3)
print('second addition:',arr1.dot(arr3))


***Mathematical function - Beyound Back Arithemetic***

In [49]:
# cmmon mathematical fubction 
arr= np.array([1,4,9,16,25])
print('Original array:',arr)

# square roots and powers
print('square root:',np.sqrt(arr))
print('square:',np.square(arr))

Original array: [ 1  4  9 16 25]
square root: [1. 2. 3. 4. 5.]
square: [  1  16  81 256 625]


**Aggregate Functions - Summarizing Your Data**

    - Aggregate functions reduce arrays to summary statistics

In [ ]:
# create a 2D array for demonsration
arr=np.arange(0,9).reshape(3,3)
print(arr)

# aggregate across entire array
print('Sum of all elements:',np.sum(arr))
print('mean of array:',np.mean(arr))
print('standard dev of the array:',np.std(arr))
print('minimum value of array:',np.min(arr))
print('max array  value:',np.max(arr))

#When you don't specify an axis, these functions operate on the flattened array, giving you a single summary value for the entire dataset.

# Axis-specific aggregation - this is where numpy shines!
print('sum along axis 0 (columns):',np.sum(arr, axis=0))
print('sum along axis 1(rows)',np.sum(arr, axis=1))


In [ ]:
# Visualizing broadcasting step by step
a = np.arange(4).reshape(4, 1)                # Shape: (4, 1)
b = np.arange(5).reshape(1, 5) 

print("Array a (4x1):\n", a)
print("Array b (1x5):\n", b)

#broadcasting creates a 4x5 result
result= a + b
print('Broadcasting result (4x5):\n', result)
