# Understanding Numpy 

In [1]:
# import all neccsarry libraries

import numpy as np
import matplotlib.pyplot as plt
import time

# Check NumPy version
print(f"NumPy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)

NumPy version: 2.3.3


creating Numpy Arrays

In [14]:
import numpy as np
import matplotlib.pyplot as plt
# 1D array: a simple sequence of numbers
# arr1d=np.array([1,2,3,4,5])
# print(arr1d)

# # 2D array: Think of this as a matrix of numbers with rows and columns
# arr2d= np.array([[1,2,3,4],[5,6,7,8]])
# print(arr2d)

# # 3D array: Think of these like a stack of 2D arrays
# arr3D= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# print(arr3D)

# # creating array with Random
# ar1D=np.random.randn(4)
# print("Array1D\n",ar1D)

# ar2D=np.random.randn(4,4)
# print("Array2D\n",ar2D)

# ar3d=np.random.randn(2,4,4)
# print("Array3D\n",ar3d)

# creating array with range of numbers
array1D=np.random.randint(1,10, size=4)
print("Rand1\n",array1D)

array2D=np.random.randint(1,31, size=(6,6))
print("rand2\n",array2D)

array3D=np.random.randint(1,41, size=(2,6,6))
print("Rand3\n",array3D)

# working with arange
range_array=np.arange(0,10,2)
print("range:\n",range_array)

line_spacing=np.linspace(1,5,5)
print("lines\n",line_spacing)


Rand1
 [5 9 1 3]
rand2
 [[ 3 17  5  3 16 22]
 [19 16 28  2 24 23]
 [ 4 10 18 23 16 12]
 [23 24  5  2 21 23]
 [ 1  8  9  4 19 25]
 [13 10  8 27 17 10]]
Rand3
 [[[11  1 33 34 33 12]
  [38  8  1 28 37 34]
  [32 19 33 23 27 19]
  [ 8  5 17 16  8 11]
  [25 34 39  9  6 22]
  [27 31 39  5 18 18]]

 [[28 30 35 11  8 17]
  [28 21 26 11  2 28]
  [26  4  8 17 17 22]
  [35 28  3  6  6 22]
  [28 12 29 22  1 10]
  [ 1 17 30 28  3 35]]]
range:
 [0 2 4 6 8]
lines
 [1. 2. 3. 4. 5.]
