In [ ]:
import numpy as np


In [2]:
Matrix_A = np.array([[2, -1], [0, 3]])
Matrix_B = np.array([[1, 4], [-2, 5]])
print("Matrix A", Matrix_A)
print("Matrix B\n", Matrix_B)


Matrix A [[ 2 -1]
 [ 0  3]]
Matrix B
 [[ 1  4]
 [-2  5]]


### QUESTION A
let's the scalers (c = 2), (d = 3)

In [3]:

## (i) c(A)
scaler_c = 2

scaler_A = scaler_c * Matrix_A
print("The scaler multiplication for Matrix A, c(A):\n", scaler_A) 

## (i) d(B)
scaler_d = 3

scaler_B = scaler_d * Matrix_B
print("The scaler multiplication for Matrix B, d(B):\n", scaler_B) 

The scaler multiplication for Matrix A, c(A):
 [[ 4 -2]
 [ 0  6]]
The scaler multiplication for Matrix B, d(B):
 [[ 3 12]
 [-6 15]]


#### (iii) (c + d)A

In [17]:
scaler_sum = scaler_c + scaler_d
for_A = scaler_sum * Matrix_A

print("(c + d)A = \n", for_A)

(c + d)A = 
 [[10 -5]
 [ 0 15]]


### QUESTION B

Verify for scaler multiplication: (c + d)(A)
<br>

(c + d)(A) = cA + dA


In [25]:
left = scaler_c * Matrix_A
right = scaler_d * Matrix_A

total = left + right
print("cA =", left)
print("dA =", right)
print("cA + dA =\n", total)

cA = [[ 4 -2]
 [ 0  6]]
dA = [[ 6 -3]
 [ 0  9]]
cA + dA =
 [[10 -5]
 [ 0 15]]


### QUESTION C

The transpose of A and B

In [27]:
transpose_A = Matrix_A.T
transpose_B = Matrix_B.T

print("Transpose A^T:\n", transpose_A)
print("Transpose B^T:\n", transpose_B)

Transpose A^T:
 [[ 2  0]
 [-1  3]]
Transpose B^T:
 [[ 1 -2]
 [ 4  5]]


###

The Determinant and Inverse of A and B

In [29]:
det_A = np.linalg.det(Matrix_A)
det_B = np.linalg.det(Matrix_B)

print("detA =", det_A)
print("detB", det_B)

detA = 6.0
detB 13.0


###
 Inverse  of the Matrix A and B

In [31]:
inv_A = np.linalg.inv(Matrix_A)
inv_B = np.linalg.inv(Matrix_B)

print("Inverse A:\n", inv_A)
print("Inverse B:\n", inv_B)

Inverse A:
 [[0.5        0.16666667]
 [0.         0.33333333]]
Inverse B:
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
